#include "ui/Lang.h"

#include <map>
#include <string>
#include <unordered_map>

#include "core/Model.h"

namespace se::lang {
namespace {

Language g_language = Language::German;

struct Entry {
    const char* de;
    const char* en;
};

// clang-format off
const Entry kTable[] = {
    // ------------------------------------------------------------- Menues
    {"Datei", "File"},
    {"Bearbeiten", "Edit"},
    {"Ansicht", "View"},
    {"Fenster", "Windows"},
    {"Hilfe", "Help"},
    {"Neues Projekt...", "New project..."},
    {"Projekt oeffnen...", "Open project..."},
    {"Speichern", "Save"},
    {"Alles speichern", "Save all"},
    {"Vault im Explorer oeffnen", "Show vault in Explorer"},
    {"Projekt schliessen", "Close project"},
    {"Beenden", "Quit"},
    {"Rueckgaengig", "Undo"},
    {"Wiederholen", "Redo"},
    {"Rueckgaengig: ", "Undo: "},
    {"Wiederholen: ", "Redo: "},
    {"Rueckgaengig / Wiederholen", "Undo / redo"},
    {"Rueckgaengig: %s", "Undo: %s"},
    {"Wiederholt: ", "Redone: "},
    {"Neue Gruppe...", "New group..."},
    {"Neues Element...", "New element..."},
    {"Neue Aktion...", "New action..."},
    {"Design", "Theme"},
    {"Hell", "Light"},
    {"Dunkel", "Dark"},
    {"Sprache / Language", "Language / Sprache"},
    {"Helles Design aktiv.", "Light theme active."},
    {"Dunkles Design aktiv.", "Dark theme active."},
    {"Sprache: Deutsch", "Language: German"},
    {"Sprache: Englisch", "Language: English"},
    {"Einstellungen / Farben", "Settings / colours"},
    {"Layout zuruecksetzen", "Reset layout"},
    {"Zeilenhoehe Timeline", "Timeline row height"},
    {"Leere Zeitraeume komprimieren", "Compress empty periods"},
    {"Automatisch speichern", "Autosave"},
    {"Gruppen-Manager", "Group manager"},
    {"Details", "Details"},
    {"Aktionen-Panel", "Actions panel"},
    {"Timeline", "Timeline"},
    {"Aktionen", "Actions"},
    {"Story Visualizer", "Story visualizer"},
    {"Connections", "Connections"},
    {"Dateimanager", "File manager"},
    {"Einstellungen", "Settings"},
    {"Tastenkuerzel", "Keyboard shortcuts"},
    {"Ueber Story Editor", "About Story Editor"},
    {"Kein Projekt", "No project"},

    // ------------------------------------------------------- Tastenkuerzel
    {"Strg+N", "Ctrl+N"},
    {"Strg+O", "Ctrl+O"},
    {"Strg+S", "Ctrl+S"},
    {"Strg+G", "Ctrl+G"},
    {"Strg+T", "Ctrl+T"},
    {"Strg+Y", "Ctrl+Y"},
    {"Strg+Z", "Ctrl+Z"},
    {"Strg+Shift+N", "Ctrl+Shift+N"},
    {"Strg+Z / Strg+Y", "Ctrl+Z / Ctrl+Y"},
    {"Strg+Mausrad", "Ctrl+wheel"},
    {"Shift+Mausrad", "Shift+wheel"},
    {"Timeline zoomen", "Zoom the timeline"},
    {"Timeline horizontal scrollen", "Scroll the timeline sideways"},
    {"Doppelklick Timeline", "Double click in timeline"},
    {"Aktion anlegen / bearbeiten", "Create / edit action"},
    {"Ziehen in Timeline", "Drag in timeline"},
    {"Aktion zeitlich verschieben", "Move action in time"},

    // -------------------------------------------------------- Allgemeines
    {"Kein Projekt geoeffnet.", "No project open."},
    {"Kein Projekt geoeffnet. Datei -> Neues Projekt.", "No project open. File -> New project."},
    {"Abbrechen", "Cancel"},
    {"Schliessen", "Close"},
    {"Bearbeiten...", "Edit..."},
    {"Umbenennen...", "Rename..."},
    {"Duplizieren", "Duplicate"},
    {"Loeschen", "Delete"},
    {"Umbenennen", "Rename"},
    {"Umben.", "Rename"},
    {"Suchen...", "Search..."},
    {"Waehlen...", "Browse..."},
    {"Waehlen", "Browse"},
    {"Uebernehmen", "Apply"},
    {"Ja, ausfuehren", "Yes, do it"},
    {"Eingabe", "Input"},
    {"Bestaetigen", "Confirm"},
    {"<keine>", "<none>"},
    {"<keins>", "<none>"},
    {"<oberste Ebene>", "<top level>"},
    {"(Kopie)", "(copy)"},
    {" (Kopie)", " (copy)"},
    {"(?)", "(?)"},
    {"nicht lesbar", "cannot be read"},
    {"Neuer Name", "New name"},
    {"Name eingeben...", "Enter a name..."},
    {"Details anzeigen", "Show details"},
    {"Auswahl leeren", "Clear selection"},
    {"Filter zuruecksetzen", "Reset filters"},
    {"Leeren", "Clear"},
    {"Alle", "All"},
    {"Elemente", "Elements"},
    {"Nichts ausgewaehlt. Element, Aktion oder Gruppe anklicken.",
     "Nothing selected. Click an element, action or group."},

    // ----------------------------------------------------------- Projekte
    {"Neues Projekt", "New project"},
    {"Projektname", "Project name"},
    {"Speicherort (Obsidian-Vault)", "Location (Obsidian vault)"},
    {"Ordner fuer den Vault waehlen", "Choose a folder for the vault"},
    {"Obsidian-Vault waehlen", "Choose an Obsidian vault"},
    {"Es wird die Standard-Struktur (Characters, Locations, Objects, ...) angelegt.",
     "The default structure (Characters, Locations, Objects, ...) will be created."},
    {"Erstellen", "Create"},
    {"In diesem Ordner liegt bereits ein Projekt - es wird geoeffnet.",
     "This folder already holds a project - opening it instead."},
    {"Projekt erstellt: ", "Project created: "},
    {"Projekt geoeffnet: ", "Project opened: "},
    {"Projekt geladen: ", "Project loaded: "},
    {"Projekt geschlossen.", "Project closed."},
    {"Projekt konnte nicht erstellt werden.", "Could not create the project."},
    {"Projekt konnte nicht geladen werden.", "Could not load the project."},
    {"Gespeichert nach ", "Saved to "},

    // ------------------------------------------------------------ Gruppen
    {"+ Gruppe", "+ Group"},
    {"+ Element", "+ Element"},
    {"Neue Gruppe", "New group"},
    {"Gruppe bearbeiten", "Edit group"},
    {"Gruppe bearbeiten (Name/Farbe)...", "Edit group (name/colour)..."},
    {"Uebergeordnete Gruppe", "Parent group"},
    {"Eigene Farbe", "Custom colour"},
    {"Farbe wird automatisch aus der Elterngruppe abgeleitet.",
     "The colour is derived from the parent group automatically."},
    {"Gruppe erstellt", "Group created"},
    {"Gruppe bearbeitet", "Group edited"},
    {"Gruppe geloescht", "Group deleted"},
    {"Gruppe loeschen", "Delete group"},
    {"Gruppe \"", "Group \""},
    {"Gruppe nicht gefunden.", "Group not found."},
    {"Gruppe: ", "Group: "},
    {"Neue Untergruppe...", "New subgroup..."},
    {"Untergruppe", "Subgroup"},
    {"Noch keine Gruppen. Lege eine an: + Gruppe", "No groups yet. Create one: + Group"},
    {" Element(e) inkl. Untergruppen werden mitgeloescht.",
     " element(s) including subgroups will be deleted as well."},
    {"Gruppenfarbe", "Group colour"},
    {"Gruppenfarbe automatisch", "Automatic group colour"},
    {"Gruppen-Farben", "Group colours"},
    {"Auto", "Auto"},
    {"Bitte zuerst eine Gruppe waehlen.", "Please select a group first."},

    // ----------------------------------------------------------- Elemente
    {"Neues Element", "New element"},
    {"Element bearbeiten", "Edit element"},
    {"Element erstellt", "Element created"},
    {"Element bearbeitet", "Element edited"},
    {"Element dupliziert", "Element duplicated"},
    {"Element geloescht", "Element deleted"},
    {"Element umbenannt", "Element renamed"},
    {"Element umbenennen", "Rename element"},
    {"Element verschieben", "Move element"},
    {"Element verschoben", "Element moved"},
    {"Element nach ", "Element moved to "},
    {" verschoben", ""},
    {"Element loeschen", "Delete element"},
    {"Element nicht gefunden.", "Element not found."},
    {"Element suchen...", "Find element..."},
    {"Verschieben nach...", "Move to..."},
    {"Verschieben", "Move"},
    {"Zielgruppe", "Target group"},
    {"\" inklusive .md-Datei loeschen?", "\" including its .md file?"},
    {"Folgende Verweise werden ungueltig:\n", "These references will break:\n"},
    {"Als Aktion in Timeline eintragen", "Add as action to the timeline"},
    {"Datei im Explorer zeigen", "Show file in Explorer"},
    {"Datei oeffnen", "Open file"},
    {"Aktion hinzufuegen", "Add action"},
    {"Erwaehnt in Aktionen", "Mentioned in actions"},
    {"Freitext", "Free text"},
    {"Beziehungen", "Relations"},
    {"Keine Verbindungen.", "No connections."},
    {"+ Verbindung", "+ Connection"},
    {"+ Eigenes Feld", "+ Custom field"},
    {"(nur hier)", "(this element only)"},
    {"Feld nur von diesem Element entfernen", "Remove the field from this element only"},
    {"Legt ein Feld an, das nur zu diesem Element gehoert - das Template der Gruppe bleibt unveraendert.",
     "Creates a field that belongs to this element only - the group template stays untouched."},
    {"Feld entfernt", "Field removed"},
    {"Feld hinzugefuegt", "Field added"},
    {"Feld geaendert", "Field changed"},
    {"Felder", "Fields"},
    {"Feldname", "Field name"},

    // ---------------------------------------------------------- Templates
    {"Template bearbeiten", "Edit template"},
    {"Template bearbeiten...", "Edit template..."},
    {"Template: ", "Template: "},
    {"Template gespeichert", "Template saved"},
    {"Template aktualisiert.", "Template updated."},
    {"Eigene Felder:", "Own fields:"},
    {"Geerbte Felder:", "Inherited fields:"},
    {"Noch keine eigenen Felder.", "No own fields yet."},
    {"+ Neues Feld", "+ New field"},
    {"Neues Feld", "New field"},
    {"Feld bearbeiten", "Edit field"},
    {"Alle speichern", "Save all"},
    {"Speichern ergaenzt fehlende Felder bei allen Elementen dieser Gruppe (inkl. Untergruppen).",
     "Saving adds missing fields to every element of this group (including subgroups)."},
    {"Felder (inkl. geerbt):", "Fields (including inherited):"},
    {"  (geerbt)", "  (inherited)"},
    {"Diese Gruppe hat noch kein Template.", "This group has no template yet."},
    {"Typ", "Type"},
    {"Pflichtfeld", "Required"},
    {"[Pflicht]", "[required]"},
    {"  Pflicht", "  required"},
    {"* Pflicht", "* required"},
    {"Pflichtfelder muessen beim Anlegen eines Elements ausgefuellt werden.",
     "Required fields must be filled in when an element is created."},
    {"Standardwert", "Default value"},
    {"Beschreibung / Hilfetext", "Description / help text"},
    {"Anzeigeformat (optional)", "Display format (optional)"},
    {"Auswahl-Optionen (eine pro Zeile)", "Choices (one per line)"},
    {"Feldname darf nicht leer sein.", "The field name cannot be empty."},
    {"Feldname existiert bereits.", "That field name already exists."},
    {"Name darf nicht leer sein.", "The name cannot be empty."},
    {"Pflichtfeld \"", "Required field \""},
    {"\" ist leer.", "\" is empty."},
    {"z.B. age, birthday, status", "e.g. age, birthday, status"},
    {"z.B. DD.MM.YYYY", "e.g. DD/MM/YYYY"},
    {"Elemente: %d", "Elements: %d"},

    // ----------------------------------------------------------- Aktionen
    {"+ Neue Aktion", "+ New action"},
    {"Neue Aktion", "New action"},
    {"Aktion bearbeiten", "Edit action"},
    {"Aktion erstellt", "Action created"},
    {"Aktion bearbeitet", "Action edited"},
    {"Aktion dupliziert", "Action duplicated"},
    {"Aktion geloescht", "Action deleted"},
    {"Aktion loeschen", "Delete action"},
    {"Aktion \"", "Action \""},
    {"Aktion nicht gefunden.", "Action not found."},
    {"Aktion verschoben", "Action moved"},
    {"Aktion verschoben auf ", "Action moved to "},
    {"Neue Aktion hier", "New action here"},
    {"Neue Aktion fuer dieses Element", "New action for this element"},
    {"Im Aktionen-Panel zeigen", "Show in actions panel"},
    {"In Timeline zeigen", "Show in timeline"},
    {"Zur Timeline", "To timeline"},
    {"Titel", "Title"},
    {"Titel darf nicht leer sein.", "The title cannot be empty."},
    {"Beschreibung / Szene", "Description / scene"},
    {"Beschreibung", "Description"},
    {"wichtig (Major)", "important (major)"},
    {"Strang", "Storyline"},
    {"Zeitpunkt", "Point in time"},
    {"Zeit relativ zu einer anderen Aktion", "Time relative to another action"},
    {"Nach", "After"},
    {"Minuten danach", "minutes later"},
    {"Ergibt: ", "Result: "},
    {"Zeitpunkt nicht lesbar (z.B. \"Tag 5, 14:00\").",
     "Point in time cannot be read (e.g. \"Day 5, 14:00\")."},
    {"Beteiligte Elemente (Charaktere, Orte, Objekte)",
     "Involved elements (characters, locations, objects)"},
    {"Beteiligte", "Involved"},
    {"Beteiligte:", "Involved:"},
    {"Beteiligt: ", "Involved: "},
    {"Beteiligte filtern", "Filter by involved"},
    {"Gewaehlt: ", "Selected: "},
    {"Tags (Komma getrennt, neue einfach eintippen)",
     "Tags (comma separated, just type new ones)"},
    {"Tags: ", "Tags: "},
    {"Tag1, Tag2, ...", "Tag1, Tag2, ..."},
    {"Vorhandene...", "Existing..."},
    {"Noch keine Tags im Projekt - einfach oben eintippen.",
     "No tags in this project yet - just type one above."},
    {"Anhaenge", "Attachments"},
    {"Anhaenge:", "Attachments:"},
    {"Anhaenge: ", "Attachments: "},
    {"Anhaenge waehlen", "Choose attachments"},
    {"Datei hinzufuegen...", "Add file..."},
    {"Entfernen", "Remove"},
    {"Attribut-Aenderungen (Mutations)", "Attribute changes (mutations)"},
    {"Attribut-Aenderungen:", "Attribute changes:"},
    {"+ Aenderung", "+ Change"},
    {"+ Eintrag", "+ Item"},
    {"Zeit: ", "Time: "},
    {"Zeit", "Time"},
    {"#", "#"},
    {"Typ: ", "Type: "},
    {"Handlungsstrang: ", "Storyline: "},
    {"  |  wichtig", "  |  important"},
    {"Volltextsuche...", "Full text search..."},
    {"Zeitraum", "Period"},
    {"%d von %d Aktionen", "%d of %d actions"},
    {"auf", "open"},
    {"zu", "close"},
    {"Eigene Aktions-Typen koennen direkt im Dropdown angelegt werden.",
     "Custom action types can be created right in the dropdown."},
    {"Eigene Handlungsstraenge koennen direkt im Dropdown angelegt werden.",
     "Custom storylines can be created right in the dropdown."},

    // ----------------------------------------------------------- Timeline
    {"Einheit", "Unit"},
    {"Zoom", "Zoom"},
    {"Komprimieren", "Compress"},
    {"Lange Zeitraeume ohne Ereignisse werden zusammengeschoben, dichte Bereiche gedehnt.",
     "Long stretches without events are squeezed together, dense areas are stretched."},
    {"Basis-Zeiteinheit der Skala", "Base time unit of the scale"},
    {"Gruppen-Filter", "Group filter"},
    {"Typ-Filter", "Type filter"},
    {"Sichtbare Hauptgruppen (Mehrfachauswahl)", "Visible top level groups (multiple choice)"},
    {"Zeitfenster", "Time window"},
    {"Keine Spuren sichtbar - Gruppen anlegen oder Filter zuruecksetzen.",
     "No tracks visible - create groups or reset the filters."},

    // ------------------------------------------------------ Story Visualizer
    {"Fokus", "Focus"},
    {"nur Wichtiges", "important only"},
    {"voller Text", "full text"},
    {"Werteaenderungen", "Value changes"},
    {"Nur-Lese-Ansicht: hier wird die Geschichte erzaehlt, nicht bearbeitet.",
     "Read only view: the story is told here, not edited."},
    {"Keine Ereignisse fuer diese Auswahl.", "No events for this selection."},
    {" vergehen", " pass"},
    {" (nicht gezeigte Ereignisse dazwischen)", " (hidden events in between)"},

    // -------------------------------------------------------- Connections
    {"Verbindung erstellen", "Create connection"},
    {"Verbindung bearbeiten", "Edit connection"},
    {"Verbindung erstellt", "Connection created"},
    {"Verbindung bearbeitet", "Connection edited"},
    {"Verbindung geloescht", "Connection deleted"},
    {"Verbindung loeschen", "Delete connection"},
    {"Verbindung nicht gefunden.", "Connection not found."},
    {"Verbindung von hier...", "Connection from here..."},
    {"Diese Verbindung loeschen?", "Delete this connection?"},
    {"Die zwei markierten verbinden", "Connect the two selected"},
    {"Von", "From"},
    {"Nach ", "To "},
    {"Von (Zeit)", "From (time)"},
    {"Bis (Zeit)", "Until (time)"},
    {"Von: ", "From: "},
    {"Bis: ", "Until: "},
    {"offen", "open"},
    {"Block", "Block"},
    {"Bloecke", "Blocks"},
    {"Block erstellen", "Create block"},
    {"Block erstellt", "Block created"},
    {"Block geloescht", "Block deleted"},
    {"Enthaltene Verbindungen:", "Connections in this block:"},
    {"Keine Verbindungen zwischen den markierten Knoten gefunden.",
     "No connections found between the selected nodes."},
    {"Fasst alle Verbindungen zwischen den markierten Knoten zu einem Block zusammen.",
     "Groups every connection between the selected nodes into one block."},
    {"Bloecke fassen zusammengehoerende Verbindungen zusammen - hier auch neu anlegbar.",
     "Blocks group related connections - new ones can be created here too."},
    {"Eigene Beziehungstypen (z.B. mentor_of) koennen direkt im Dropdown angelegt werden.",
     "Custom relation types (e.g. mentor_of) can be created right in the dropdown."},
    {"Auto-Layout", "Auto layout"},
    {"Grad", "Degree"},
    {"Keine Elemente vorhanden.", "No elements yet."},
    {"Linksklick = waehlen (Strg = mehrere), ziehen = verschieben, Rad = Zoom",
     "Left click = select (Ctrl = several), drag = move, wheel = zoom"},

    // ------------------------------------------------------- Dateimanager
    {"Strukturiert", "Structured"},
    {"Rohe Dateien", "Raw files"},
    {"Datei hochladen...", "Upload file..."},
    {"Neuer Ordner...", "New folder..."},
    {"Neuer Ordner", "New folder"},
    {"Vault oeffnen", "Open vault"},
    {"Dateien in den Vault kopieren", "Copy files into the vault"},
    {"Datei waehlen", "Choose a file"},
    {"Keine Datei ausgewaehlt.", "No file selected."},
    {"Im Explorer oeffnen", "Open in Explorer"},
    {"Oeffnen", "Open"},
    {"Datei umbenennen", "Rename file"},
    {"Datei verschieben", "Move file"},
    {"Datei loeschen", "Delete file"},
    {"Datei geloescht.", "File deleted."},
    {"Datei verknuepft", "File linked"},
    {"Datei hinzugefuegt: ", "File added: "},
    {"Zielordner (relativ)", "Target folder (relative)"},
    {"Mit Element verknuepfen:", "Link to element:"},
    {"Verknuepfen", "Link"},
    {"Mit ", "Linked to "},
    {" verknuepft.", "."},
    {"Rohinhalt (nur Ansicht):", "Raw content (view only):"},
    {"Bild konnte nicht geladen werden.", "The image could not be loaded."},
    {"Ordner erstellt: ", "Folder created: "},
    {"Ordner existiert nicht.", "That folder does not exist."},
    {"Ordner ist leer.", "The folder is empty."},
    {"(Vault-Wurzel)", "(vault root)"},
    {"Umbenannt in ", "Renamed to "},
    {"Umbenennen fehlgeschlagen.", "Rename failed."},
    {"Verschieben fehlgeschlagen.", "Move failed."},
    {"Verschoben nach ", "Moved to "},
    {"Loeschen fehlgeschlagen.", "Delete failed."},
    {"Konnte Datei nicht kopieren: ", "Could not copy file: "},
    {"\" wirklich loeschen?", "\" for good?"},
    {"Achtung: .md-Dateien gehoeren zu Elementen. Loeschen kann Verweise brechen.",
     "Careful: .md files belong to elements. Deleting one can break references."},
    {" Datei(en) empfangen - Dateimanager oeffnen.",
     " file(s) received - open the file manager."},

    // ------------------------------------------------------ Einstellungen
    {"Farben", "Colours"},
    {"Text primaer", "Text primary"},
    {"Text sekundaer", "Text secondary"},
    {"Hintergrund", "Background"},
    {"Panel", "Panel"},
    {"Akzent", "Accent"},
    {"Warnung", "Warning"},
    {"Erfolg", "Success"},
    {"Fehler", "Error"},
    {"Timeline Hintergrund", "Timeline background"},
    {"Timeline Raster", "Timeline grid"},
    {"Timeline Spur (alternierend)", "Timeline row (alternating)"},
    {"Timeline Lineal", "Timeline ruler"},
    {"Auswahl", "Selection"},
    {"Hover", "Hover"},
    {"Ghost (Drag)", "Ghost (drag)"},
    {"Verbindungslinie", "Connection line"},
    {"Knoten-Umriss", "Node outline"},
    {"Design neu laden", "Reload theme"},
    {"Verwirft eigene Farbaenderungen und stellt das gewaehlte Design wieder her.",
     "Discards custom colour changes and restores the selected theme."},
    {"Setzt alle Farben auf das gewaehlte Design zurueck. Einzelne Farben lassen sich ",
     "Resets every colour to the selected theme. Individual colours can be "},
    {"darunter weiter anpassen.", "adjusted below."},
    {"Spurhoehe", "Row height"},
    {"Breite Spurtitel", "Track title width"},
    {"Min. Abstand", "Min. spacing"},
    {"Max. Abstand", "Max. spacing"},
    {"Allgemein", "General"},
    {"Schriftgroesse wirkt nach Neustart:", "Font size applies after a restart:"},
    {"Einstellungen speichern", "Save settings"},
    {"Einstellungen gespeichert.", "Settings saved."},
    {"Eigene Listen", "Custom lists"},
    {"Aktions-Typen", "Action types"},
    {"Beziehungstypen", "Relation types"},
    {"Handlungsstraenge", "Storylines"},
    {"Aktions-Typen, Beziehungstypen und Handlungsstraenge gehoeren dir - hier oder direkt ",
     "Action types, relation types and storylines are yours - create them here or right "},
    {"im jeweiligen Dropdown anlegen.", "in the matching dropdown."},
    {"So oft wird der Eintrag im Projekt verwendet.", "How often the entry is used in the project."},
    {"Eintrag umbenennen", "Rename entry"},
    {"Eintrag umbenannt", "Entry renamed"},
    {"Eintrag loeschen", "Delete entry"},
    {"Eintrag geloescht", "Entry deleted"},
    {"Eintrag hinzugefuegt", "Entry added"},
    {"Neuer Eintrag...", "New entry..."},
    {"Eigenen Eintrag hinzufuegen (Enter geht auch)", "Add a custom entry (Enter works too)"},
    {"Eigener Eintrag:", "Custom entry:"},
    {" Eintraege benutzen ihn und werden auf \"",
     " entries use it and will be set to \""},
    {"\" gesetzt.", "\"."},
    {"\" loeschen?", "\"?"},
    {"\" zurueckgesetzt.", "\" restored."},
    {"Design \"", "Theme \""},

    // ------------------------------------------- Manuskript: Leiste und Suche
    {"Text bearbeiten - Marken sind sichtbar.", "Edit the text - markers are visible."},
    {"So liest sich die Geschichte fertig - alle Werte sind eingesetzt.",
     "This is how the finished story reads - all values are filled in."},
    {"Elemente, Werte, Aktionen und Zeitpunkte in den Text setzen - ohne "
     "Sonderzeichen tippen zu muessen.",
     "Put elements, values, actions and points in time into the text - "
     "without typing any special characters."},
    {"Element (Figur, Ort, Ding)", "Element (character, place, thing)"},
    {"Wert eines Elements", "Value of an element"},
    {"Aktion verknuepfen", "Link an action"},
    {"Aktion aus diesem Absatz", "Action from this paragraph"},
    {"Legt eine Aktion zum Zeitpunkt dieser Stelle an und verknuepft sie.",
     "Creates an action at the point in time of this spot and links it."},
    {"Zeitpunkt weiterstellen", "Move time on"},
    {"Nichts gefunden.", "Nothing found."},
    {"Dieses Element hat keine Felder.", "This element has no fields."},
    {"Zurueck", "Back"},
    {"Format", "Format"},
    {"Ueberschriften und Hervorhebungen.", "Headings and emphasis."},
    {"Kapitel", "Chapter"},
    {"Neues Kapitel", "New chapter"},
    {"Szene", "Scene"},
    {"Neue Szene", "New scene"},
    {"Szenenwechsel", "Scene break"},
    {"Erscheint links in der Gliederung und im Word-Export als Ueberschrift.",
     "Shows up in the outline on the left and as a heading in the Word "
     "export."},
    {"Eine Trennung mitten im Kapitel - im Export als * * * zentriert.",
     "A break inside a chapter - exported as a centred * * *."},
    {"Fett", "Bold"},
    {"Kursiv", "Italic"},
    {"Strg+B", "Ctrl+B"},
    {"Strg+I", "Ctrl+I"},
    {"Markierten Text hervorheben - ohne Auswahl schreibst du zwischen den "
     "Zeichen weiter.",
     "Emphasises the selected text - without a selection you keep typing "
     "between the markers."},
    {"Suchen", "Find"},
    {"Stellen im Text finden und ersetzen (Strg+F).",
     "Find and replace spots in the text (Ctrl+F)."},
    {"Im Text suchen...", "Search the text..."},
    {"Ersetzen durch...", "Replace with..."},
    {"Ersetzen", "Replace"},
    {"Alle ersetzen", "Replace all"},
    {" Stellen ersetzt.", " spots replaced."},
    {"Naechster Treffer (F3)", "Next hit (F3)"},
    {"Vorheriger Treffer (Shift+F3)", "Previous hit (Shift+F3)"},
    {"kein Treffer", "no hit"},
    {"Gross/klein", "Aa"},
    {"Gross- und Kleinschreibung beachten", "Match case"},
    {"Als Word speichern...", "Save as Word..."},
    {"Gespeichert", "Saved"},
    {"Alles steht im Vault.", "Everything is in the vault."},
    {"Wird gleich von selbst geschrieben - Klick speichert sofort.",
     "Will be written by itself in a moment - click to save right now."},
    {"Automatisches Speichern ist aus. Klicken oder Strg+S.",
     "Autosave is off. Click or press Ctrl+S."},
    {"Klick springt an die Stelle im Text.", "A click jumps to that spot in the text."},
    {"Kapitel und Zeitpunkte aus dem Menue \"Format\" bzw. \"Einfuegen\" "
     "erscheinen hier.",
     "Chapters and points in time from the \"Format\" and \"Insert\" menus "
     "show up here."},
    {"Der Absatz am Cursor ist leer.", "The paragraph at the cursor is empty."},
    {"Einfach losschreiben - wie in jedem Textprogramm. Figuren, Werte, "
     "Zeitpunkte und Ueberschriften setzt du oben ueber \"Einfuegen\" und "
     "\"Format\" ein. Das \"?\" erklaert den Rest.",
     "Just start writing - like in any word processor. Characters, values, "
     "points in time and headings go in via \"Insert\" and \"Format\" above. "
     "The \"?\" explains the rest."},
    {"Wie das Schreiben hier funktioniert", "How writing works here"},
    {"Kurz erklaert, wie dieses Fenster funktioniert.",
     "A short explanation of how this window works."},
    {"Schreib einfach los wie in jedem Textprogramm. Alles Weitere setzt die "
     "Leiste oben fuer dich ein - du musst dir keine Sonderzeichen merken.",
     "Just start writing like in any word processor. The bar above inserts "
     "everything else for you - there are no special characters to memorise."},
    {"Die Marken sind nur im Schreibmodus zu sehen. Im Lesemodus und in der "
     "Word-Datei steht der fertige Text.",
     "Markers only show while writing. Reading mode and the Word file carry "
     "the finished text."},
    {"Eine Figur, ein Ort, ein Ding nennen", "Name a character, a place, a thing"},
    {"Einfuegen > Element - oder einfach @ tippen und weiterschreiben.",
     "Insert > Element - or simply type @ and keep going."},
    {"Einen Wert einsetzen (Alter, Titel, Zustand)", "Insert a value (age, title, condition)"},
    {"Einfuegen > Wert eines Elements. Im Text steht dann immer der Wert, "
     "der zu diesem Zeitpunkt der Geschichte gilt.",
     "Insert > Value of an element. The text then always carries the value "
     "that applies at that point in the story."},
    {"Zeit vergehen lassen", "Let time pass"},
    {"Einfuegen > Zeitpunkt. Die Zeit bleibt stehen, bis du sie "
     "weiterstellst.",
     "Insert > Point in time. Time stays put until you move it on."},
    {"Eine Stelle als Ereignis merken", "Record a spot as an event"},
    {"Einfuegen > Aktion aus diesem Absatz - Beteiligte und Zeitpunkt kommen "
     "aus dem Text.",
     "Insert > Action from this paragraph - involved elements and time come "
     "from the text."},
    {"Kapitel und Szenen gliedern", "Structure chapters and scenes"},
    {"Format > Kapitel bzw. Szene. Beides erscheint links in der Gliederung.",
     "Format > Chapter or Scene. Both show up in the outline on the left."},
    {"Hervorheben", "Emphasise"},
    {"Format > Fett / Kursiv, oder Strg+B und Strg+I.",
     "Format > Bold / Italic, or Ctrl+B and Ctrl+I."},
    {"Etwas wiederfinden", "Find something again"},
    {"Suchen (Strg+F) - findet auch Namen und Marken.",
     "Find (Ctrl+F) - it also finds names and markers."},

    // ---------------------------------------------------------- Manuskript
    {"Manuskript", "Manuscript"},
    {"Schreiben", "Write"},
    {"Lesen", "Read"},
    {"Gliederung", "Outline"},
    {"Aktion aus Absatz", "Action from paragraph"},
    {"Macht aus dem Absatz am Cursor eine Aktion - Beteiligte und Zeitpunkt kommen aus dem Text.",
     "Turns the paragraph at the cursor into an action - involved elements and time come from the text."},
    {"Zeitmarke", "Time marker"},
    {"Ab dieser Stelle gilt ein neuer Zeitpunkt - Werte im Text richten sich danach. Im fertigen Text ist die Marke nicht zu sehen.",
     "From here on a new point in time applies - values in the text follow it. The marker is not "
     "part of the finished text."},
    {"Woerter", "words"},
    {"Ueberschriften mit ## und Zeitmarken mit # erscheinen hier.",
     "Headings with ## and time markers with # show up here."},
    {"Einfach losschreiben. @Name verweist auf ein Element, @Name.feld setzt dessen Wert ein. Wie viel Zeit inzwischen vergangen ist, stellst du oben ueber \"Zeit: ...\" weiter.",
     "Just start writing. @Name refers to an element, @Name.field inserts its value. How much "
     "time has passed meanwhile is set above via \"Time: ...\"."},
    {"Der Zeitpunkt, an dem die Geschichte an dieser Stelle steht. Klicken, um die Zeit ab hier weiterzustellen.",
     "The point in time the story is at in this spot. Click to move time on from here."},
    {"Die Zeit laeuft nicht von allein weiter: sie bleibt stehen, bis du sie weiterstellst. Ab der Marke gilt der neue Zeitpunkt fuer alles, was danach im Text kommt.",
     "Time does not move on by itself: it stays put until you move it. From the marker on, the "
     "new point in time applies to everything that follows in the text."},
    {"Hier gilt gerade: ", "Currently in effect here: "},
    {"Weiter um:", "Move on by:"},
    {"Oder fester Zeitpunkt:", "Or a fixed point in time:"},
    {"+ 1 Stunde", "+ 1 hour"},
    {"+ 6 Stunden", "+ 6 hours"},
    {"z.B. \"Tag 5, 14:00\" oder \"Jahr 2, Monat 3, Tag 15\"",
     "e.g. \"Day 5, 14:00\" or \"Year 2, Month 3, Day 15\""},
    {"Enter uebernimmt, Pfeile waehlen, Esc schliesst", "Enter accepts, arrows choose, Esc closes"},
    {"Feld waehlen - Enter uebernimmt", "Pick a field - Enter accepts"},
    {"Feld ist leer - es wird der Name benutzt.", "The field is empty - the name is used instead."},
    {"Marken zeigen", "Show markers"},
    {"Als Word", "As Word"},
    {"Manuskript als Word (.docx)...", "Manuscript as Word (.docx)..."},
    {"Manuskript als Word-Datei speichern", "Save manuscript as a Word file"},
    {"Schreibt die fertige Geschichte: Werte sind fest eingesetzt, Zeit- und Aktionsmarken stehen nicht darin.",
     "Writes the finished story: values are baked in, time and action markers are not part of it."},
    {"Word-Datei geschrieben: ", "Word file written: "},
    {"Word-Datei konnte nicht geschrieben werden.", "Could not write the Word file."},
    {"Aktion setzen", "Place action"},
    {"Aktion suchen...", "Find action..."},
    {"Keine passende Aktion.", "No matching action."},
    {"+ Neue Aktion hier", "+ New action here"},
    {"Aktion waehlen - Enter uebernimmt", "Pick an action - Enter accepts"},
    {"Setzt an dieser Stelle eine Marke auf eine Aktion - im fertigen Text unsichtbar, dient nur der Organisation. Kurzform beim Tippen: !",
     "Places a marker for an action at this spot - invisible in the finished text, purely for "
     "organisation. Shortcut while typing: !"},
    {"Zeitleiste", "Timeline"},

    {"Zum Anfang", "To the beginning"},
    {"Zum Ende", "To the end"},
    {"Gueltige Verbindungen zu diesem Zeitpunkt", "Connections valid at this point in time"},
    {"Zeitpunkt eintippen, Enter uebernimmt", "Type a point in time, Enter applies"},
    {"Es werden nur Verbindungen gezeigt, die zu diesem Zeitpunkt gelten.",
     "Only connections that apply at this point in time are shown."},
    {"Nur zur Orientierung beim Lesen - im Export steht sie nie.",
     "Only for orientation while reading - never part of the export."},
    {"Hier gilt: ", "Applies here: "},
    {"Einfuegen", "Insert"},
    {"+ 1 h", "+ 1 h"},
    {"+ 6 h", "+ 6 h"},
    {"+ 1 Tag", "+ 1 day"},
    {"+ 3 Tage", "+ 3 days"},
    {"+ 1 Woche", "+ 1 week"},
    {"+ 1 Monat", "+ 1 month"},
    {"Nicht gefunden - Name pruefen.", "Not found - check the name."},
    {"Aktion angelegt: ", "Action created: "},

    // ------------------------------------------------- Verbindungstypen
    {"Verbindungstypen", "Connection types"},
    {"Verbindungstypen verwalten...", "Manage connection types..."},
    {"Typen verwalten...", "Manage types..."},
    {"Neuer Verbindungstyp", "New connection type"},
    {"Verbindungstyp bearbeiten", "Edit connection type"},
    {"Verbindungstyp erstellt", "Connection type created"},
    {"Verbindungstyp bearbeitet", "Connection type edited"},
    {"Verbindungstyp geloescht", "Connection type deleted"},
    {"Verbindungstyp loeschen", "Delete connection type"},
    {"+ Neuer Typ", "+ New type"},
    {"Noch keine Verbindungstypen.", "No connection types yet."},
    {"Name der Verbindung", "Name of the connection"},
    {"z.B. Person an Ort", "e.g. person at place"},
    {"Rollen - wer oder was wird hier verbunden?", "Roles - who or what is connected here?"},
    {"Pro Rolle festlegen, aus welchen Gruppen gewaehlt werden darf.",
     "For each role, pick which groups may be chosen from."},
    {"Rollenname", "Role name"},
    {"Rolle", "Role"},
    {"+ Rolle", "+ Role"},
    {"alle Gruppen", "all groups"},
    {"Ueber die Timeline setzbar (zeitlich)", "Can be set on the timeline (temporal)"},
    {"Zeitliche Verbindungen gelten ab einem Zeitpunkt, koennen beliebig oft neu gesetzt werden und erscheinen als Band in der Timeline.",
     "Temporal connections apply from a point in time, can be set again as often as you like and "
     "show up as a band in the timeline."},
    {"pro Element nur eine gleichzeitig", "only one at a time per element"},
    {"Beim Setzen einer neuen Verbindung endet die vorherige automatisch - passend z.B. fuer einen Aufenthaltsort.",
     "Setting a new connection ends the previous one automatically - fits a whereabouts, for example."},
    {"Band in der Timeline zeichnen", "Draw a band in the timeline"},
    {"Band laeuft in der Spur von", "Band runs in the track of"},
    {"Beschriftet mit", "Labelled with"},
    {"zeitlich, exklusiv", "temporal, exclusive"},
    {"zeitlich", "temporal"},
    {"fest", "fixed"},
    {" gesetzte Verbindungen werden mitgeloescht.", " connections using it will be deleted as well."},
    {"Eine Vorlage legt fest, was womit verbunden wird - und ob sich das ueber die Zeit aendern darf.",
     "A template decides what gets connected to what - and whether it may change over time."},
    {"Zuerst einen Verbindungstyp anlegen.", "Create a connection type first."},
    {"Ab", "From"},
    {"Bis", "Until"},
    {"leer = von Anfang an", "empty = from the start"},
    {"leer = bis zur naechsten Setzung", "empty = until the next one is set"},
    {"leer = offen", "empty = open ended"},
    {"Baender", "Bands"},
    {"Verbindungen als Band zeigen", "Show connections as a band"},
    {"Setzen: ", "Set: "},
    {"Stand an Tag", "State on day"},
    {"Verbindungstypen sind eigene Vorlagen mit Rollen - sie werden im eigenen Fenster verwaltet.",
     "Connection types are your own templates with roles - they are managed in their own window."},
    // ---------------------------------------------- externe Aenderungen
    {"Externe Aenderung", "External change"},
    {"Die Datei \"%s\" wurde ausserhalb des Programms veraendert!",
     "The file \"%s\" was changed outside of the program!"},
    {"Die Aenderung kann inkonsistent mit den Programm-Daten sein. .md-Dateien sollten nur ueber ",
     "That change may be inconsistent with the program data. .md files should only be edited "},
    {"die UI bearbeitet werden.", "through the UI."},
    {"Inhalt auf der Festplatte:", "Content on disk:"},
    {"Verwirft die Daten im Programm und uebernimmt die Datei.",
     "Discards the data in the program and takes the file."},
    {"Uebernimmt externe Feldwerte, behaelt zusaetzliche Programm-Felder.",
     "Takes external field values, keeps additional program fields."},
    {"Ignoriert die externe Aenderung und schreibt die Programm-Daten zurueck.",
     "Ignores the external change and writes the program data back."},
    {"Externe Datei geladen", "External file loaded"},
    {"Externe Datei zusammengefuehrt", "External file merged"},
    {"Externe Version uebernommen.", "External version applied."},
    {"Zusammengefuehrt.", "Merged."},
    {"Externe Aenderung verworfen.", "External change discarded."},

    // ---------------------------------------------------------- Ueber/Hilfe
    {"Schreib-Management fuer komplexe Geschichten.",
     "Writing management for complex stories."},
    {"Speicherung: Obsidian-Vault (Markdown + JSON)", "Storage: Obsidian vault (Markdown + JSON)"},
    {"Wichtig: .md-Dateien werden ausschliesslich vom Programm geschrieben. Externe ",
     "Important: .md files are written by the program only. External "},
    {"Aenderungen werden erkannt und abgefragt.", "changes are detected and confirmed with you."},
    {"DirectX 11 konnte nicht initialisiert werden.", "DirectX 11 could not be initialised."},

    // ------------------------------------ Manuskript: Menueband und Seite
    {"(leer)", "(empty)"},
    {"Weitere Farben...", "More colours..."},
    {"Aus der Zwischenablage einfuegen (Strg+V)", "Paste from the clipboard (Ctrl+V)"},
    {"Ausschneiden", "Cut"},
    {"Strg+X", "Ctrl+X"},
    {"Kopieren", "Copy"},
    {"Strg+C", "Ctrl+C"},
    {"Strg+V", "Ctrl+V"},
    {"Strg+U", "Ctrl+U"},
    {"Zwischenablage", "Clipboard"},
    {"Schriftart", "Font"},
    {"Schriftgrad (Punkt)", "Font size (points)"},
    {"Schriftgrad waehlen", "Choose font size"},
    {"Schrift vergroessern (Strg+Umschalt+>)", "Grow font (Ctrl+Shift+>)"},
    {"Schrift verkleinern (Strg+<)", "Shrink font (Ctrl+<)"},
    {"Formatierung loeschen (Strg+Leertaste)", "Clear formatting (Ctrl+Space)"},
    {"Fett (Strg+B)", "Bold (Ctrl+B)"},
    {"Kursiv (Strg+I)", "Italic (Ctrl+I)"},
    {"Unterstrichen (Strg+U)", "Underline (Ctrl+U)"},
    {"Unterstrichen", "Underline"},
    {"Durchgestrichen", "Strikethrough"},
    {"Tiefgestellt (Strg+#)", "Subscript (Ctrl+#)"},
    {"Hochgestellt (Strg++)", "Superscript (Ctrl++)"},
    {"Texthervorhebungsfarbe", "Text highlight colour"},
    {"Farbe fuer die Hervorhebung waehlen", "Choose the highlight colour"},
    {"Keine Farbe", "No colour"},
    {"Schriftfarbe", "Font colour"},
    {"Schriftfarbe waehlen", "Choose the font colour"},
    {"Automatisch", "Automatic"},
    {"Aufzaehlung", "Bullets"},
    {"Nummerierung", "Numbering"},
    {"Zeilenabstand", "Line spacing"},
    {"Marken anzeigen: Zeitpunkte und Aktionen auch im Lesemodus", "Show marks: points in time and actions in reading mode too"},
    {"Szenenwechsel einfuegen", "Insert scene break"},
    {"Absatz", "Paragraph"},
    {"Formatvorlagen", "Styles"},
    {"Standard", "Normal"},
    {"Fliesstext", "Body text"},
    {"Titel des Werks", "Title of the work"},
    {"Kapitelueberschrift - erscheint im Navigationsbereich und in Word als Ueberschrift 1", "Chapter heading - shows in the navigation pane and becomes Heading 1 in Word"},
    {"Szenenueberschrift - eingerueckt im Navigationsbereich, in Word Ueberschrift 2", "Scene heading - indented in the navigation pane, Heading 2 in Word"},
    {"Linksbuendig (Strg+L)", "Align left (Ctrl+L)"},
    {"Zentriert (Strg+E)", "Centre (Ctrl+E)"},
    {"Rechtsbuendig (Strg+R)", "Align right (Ctrl+R)"},
    {"Blocksatz (Strg+J)", "Justify (Ctrl+J)"},
    {"Stellen im Text finden (Strg+F)", "Find places in the text (Ctrl+F)"},
    {"Suchen und ersetzen (Strg+H)", "Find and replace (Ctrl+H)"},
    {"Element", "Element"},
    {"Figur, Ort oder Ding einsetzen - schneller: @ tippen", "Insert a character, place or thing - faster: type @"},
    {"Wert", "Value"},
    {"Wert eines Feldes einsetzen - im Text steht, was zu diesem Zeitpunkt gilt", "Insert a field value - the text shows what is true at this point in time"},
    {"Verweise", "References"},
    {"Aktion", "Action"},
    {"Aktion mit dieser Stelle verknuepfen", "Link an action to this spot"},
    {"Aus Absatz", "From paragraph"},
    {"Handlung", "Plot"},
    {"Die Zeit der Geschichte ab hier weiterstellen", "Move the story's time on from here"},
    {"Lesezeichen", "Bookmark"},
    {"Diese Stelle merken - erscheint im Navigationsbereich", "Remember this spot - shows in the navigation pane"},
    {"Kommentar", "Comment"},
    {"Eine Notiz an diese Stelle haengen - steht nie im fertigen Text", "Attach a note to this spot - never part of the finished text"},
    {"Text", "Text"},
    {"Seitenraender", "Margins"},
    {"Abstand des Textes zum Blattrand", "Distance between text and paper edge"},
    {"Papierformat", "Paper size"},
    {"Seite einrichten", "Page setup"},
    {"Abstand zwischen den Zeilen", "Space between lines"},
    {"Schmal (1,27 cm)", "Narrow (1.27 cm)"},
    {"Mittel (1,9 cm)", "Moderate (1.9 cm)"},
    {"Normal (2,5 cm)", "Normal (2.5 cm)"},
    {"Breit (3,5 cm)", "Wide (3.5 cm)"},
    {"Grundschrift", "Base font"},
    {"Schrift fuer den ganzen Text - auch im Word-Export", "Font for the whole text - also in the Word export"},
    {"Groesse", "Size"},
    {"Dokument", "Document"},
    {"Seiten", "Pages"},
    {"Einzelne Seiten wie auf Papier", "Separate pages like on paper"},
    {"Endlos", "Continuous"},
    {"Ein durchgehendes Blatt ueber die ganze Breite", "One continuous sheet across the full width"},
    {"Keine Kommentare im Text.", "No comments in the text."},
    {"Neuer Kommentar", "New comment"},
    {"Eine Notiz an diese Stelle haengen", "Attach a note to this spot"},
    {"Vorheriger", "Previous"},
    {"Zum vorherigen Kommentar", "Go to the previous comment"},
    {"Naechster", "Next"},
    {"Zum naechsten Kommentar", "Go to the next comment"},
    {"Markierten Kommentar bearbeiten", "Edit the selected comment"},
    {"Markierten Kommentar loeschen", "Delete the selected comment"},
    {"Kommentare", "Comments"},
    {"Diese Stelle merken", "Remember this spot"},
    {"Gehe zu", "Go to"},
    {"Zu einem Lesezeichen springen", "Jump to a bookmark"},
    {"(ohne Namen)", "(no name)"},
    {"Noch keine Lesezeichen.", "No bookmarks yet."},
    {"Woerter zaehlen", "Word count"},
    {"Seiten, Woerter, Zeichen und Absaetze", "Pages, words, characters and paragraphs"},
    {"Dokumentpruefung", "Proofing"},
    {"Lesemodus", "Read mode"},
    {"Seitenlayout", "Print layout"},
    {"Schreiben auf Seiten wie auf Papier", "Write on pages like on paper"},
    {"Ansichten", "Views"},
    {"Lineal", "Ruler"},
    {"Lineal ueber der Seite", "Ruler above the page"},
    {"Navigationsbereich", "Navigation pane"},
    {"Kapitel, Szenen, Zeitpunkte und Lesezeichen links", "Chapters, scenes, points in time and bookmarks on the left"},
    {"Marken", "Marks"},
    {"Zeitpunkte und Aktionen auch im Lesemodus zeigen", "Show points in time and actions in reading mode too"},
    {"Anzeigen", "Show"},
    {"Vergroesserung waehlen (Strg+Mausrad)", "Choose magnification (Ctrl+wheel)"},
    {"Originalgroesse", "Actual size"},
    {"Eine Seite", "One page"},
    {"Die ganze Seite sichtbar", "Show the whole page"},
    {"Seitenbreite", "Page width"},
    {"Seite so breit wie das Fenster", "Page as wide as the window"},
    {"Teilen", "Split"},
    {"Zwei Stellen desselben Textes uebereinander", "Two places of the same text, one above the other"},
    {"Nur der Text - Menueband und Navigationsbereich verschwinden", "Only the text - ribbon and navigation pane disappear"},
    {"Alles in den Vault schreiben (Strg+S)", "Write everything to the vault (Ctrl+S)"},
    {"Schreibt die fertige Geschichte als .docx: Werte sind eingesetzt, Formatierung bleibt, Marken, Lesezeichen und Kommentare stehen nicht darin.", "Writes the finished story as .docx: values are filled in, formatting stays, marks, bookmarks and comments are left out."},
    {"Farben, Schriftgroesse der Oberflaeche, Speichern", "Colours, interface font size, saving"},
    {"Programm", "Application"},
    {"Speichern (Strg+S)", "Save (Ctrl+S)"},
    {"Rueckgaengig (Strg+Z)", "Undo (Ctrl+Z)"},
    {"Wiederholen (Strg+Y)", "Redo (Ctrl+Y)"},
    {"Start", "Home"},
    {"Layout", "Layout"},
    {"Ueberpruefen", "Review"},
    {"Menueband anzeigen", "Show the ribbon"},
    {"Menueband ausblenden", "Hide the ribbon"},
    {"Navigation", "Navigation"},
    {"Kapitel, Szenen, Zeitpunkte und Lesezeichen erscheinen hier.", "Chapters, scenes, points in time and bookmarks appear here."},
    {"Seite %d von %d", "Page %d of %d"},
    {"%zu von %zu Woertern", "%zu of %zu words"},
    {"%zu Woerter", "%zu words"},
    {"Zoom (Strg+Mausrad)", "Zoom (Ctrl+wheel)"},
    {"Klick: 100 %", "Click: 100 %"},
    {"Kommentare stehen nie im fertigen Text.", "Comments are never part of the finished text."},
    {"Nicht im fertigen Text - in der Word-Datei steht der Kommentar am Rand.",
     "Not part of the finished text - in the Word file the comment sits in the margin."},
    {"Eine Notiz an diese Stelle haengen - nicht im fertigen Text, in Word am Rand",
     "Attach a note to this spot - not part of the finished text, in Word in the margin"},
    {"Schreibt die fertige Geschichte als .docx: Werte sind eingesetzt, Formatierung bleibt, Kommentare stehen am Rand, Lesezeichen werden Textmarken, Zeit- und Aktionsmarken fallen weg.",
     "Writes the finished story as .docx: values are filled in, formatting stays, comments go into the margin, bookmarks become Word bookmarks, time and action markers are left out."},
    {"Name, z.B. \"Hier weiter\"", "Name, e.g. \"Continue here\""},
    {"Setzen", "Set"},
    {"Statistik", "Statistics"},
    {"Zeichen (ohne Leerzeichen)", "Characters (no spaces)"},
    {"Zeichen (mit Leerzeichen)", "Characters (with spaces)"},
    {"Absaetze", "Paragraphs"},
    {"Element einfuegen", "Insert element"},
    {"Kommentar hinzufuegen", "Add comment"},
    {"Lesezeichen setzen", "Set bookmark"},
    {"Formatieren", "Formatting"},
    {"Start: Schriftart, Groesse, Fett (Strg+B), Kursiv (Strg+I), Unterstrichen (Strg+U), Farbe, Hervorhebung.", "Home: font, size, bold (Ctrl+B), italic (Ctrl+I), underline (Ctrl+U), colour, highlight."},
    {"Ueberschriften", "Headings"},
    {"Start > Formatvorlagen: Titel, Kapitel, Szene. Sie erscheinen links im Navigationsbereich.", "Home > Styles: title, chapter, scene. They appear in the navigation pane on the left."},
    {"Ausrichten und Listen", "Alignment and lists"},
    {"Start > Absatz: links, zentriert (Strg+E), rechts (Strg+R), Blocksatz (Strg+J), Aufzaehlung, Nummerierung.", "Home > Paragraph: left, centre (Ctrl+E), right (Ctrl+R), justify (Ctrl+J), bullets, numbering."},
    {"Einfuegen > Wert. Im Text steht dann immer der Wert, der zu diesem Zeitpunkt der Geschichte gilt.", "Insert > Value. The text then always shows the value that is true at this point of the story."},
    {"Einfuegen > Zeitpunkt. Die Zeit bleibt stehen, bis du sie weiterstellst.", "Insert > Point in time. Time stands still until you move it on."},
    {"Einfuegen > Aus Absatz - Beteiligte und Zeitpunkt kommen aus dem Text.", "Insert > From paragraph - participants and time come from the text."},
    {"Lesezeichen und Kommentare", "Bookmarks and comments"},
    {"Ueberpruefen: Kommentar an die Stelle haengen, Lesezeichen setzen und anspringen.", "Review: attach a comment to a spot, set bookmarks and jump to them."},
    {"Seite und Ansicht", "Page and view"},
    {"Layout: Raender, Format, Zeilenabstand. Ansicht: Lesemodus, Lineal, Zoom (Strg+Mausrad), geteilte Ansicht, Fokus.", "Layout: margins, paper size, line spacing. View: read mode, ruler, zoom (Ctrl+wheel), split view, focus."},
    {"Suchen (Strg+F), Ersetzen (Strg+H) - findet auch Namen und Marken.", "Find (Ctrl+F), replace (Ctrl+H) - also finds names and markers."},
    {"Schreib einfach los wie in Word. Das Menueband oben formatiert, was du markiert hast - ohne Auswahl gilt das Format fuer das, was du als Naechstes tippst.", "Just start writing like in Word. The ribbon formats what you have selected - without a selection the format applies to what you type next."},
    {"Marken, Lesezeichen und Kommentare sind nur beim Schreiben zu sehen. Im Lesemodus und in der Word-Datei steht der fertige Text.", "Markers, bookmarks and comments are only visible while writing. Read mode and the Word file show the finished text."},
    {"Strg+Klick oeffnet die Details.", "Ctrl+click opens the details."},
    {"Strg+Klick zeigt die Aktion.", "Ctrl+click shows the action."},
    {"Klick bearbeitet den Kommentar.", "Click to edit the comment."},
    {"Ab hier gilt dieser Zeitpunkt der Geschichte.", "From here on, this point in the story's time applies."},
    {"Manuskript: Blatt", "Manuscript: page"},
    {"Manuskript: Schrift", "Manuscript: text"},
    {"Manuskript: Arbeitsflaeche", "Manuscript: workspace"},
    // ---------------------------------- Manuskript: Rechtschreibung und AutoKorrektur
    {"Deutsch", "German"},
    {"Englisch", "English"},
    {"Varianten", "Variants"},
    {"Rechtschreibung", "Spelling"},
    {"Unbekannte Woerter rot unterwellen - Rechtsklick zeigt Vorschlaege", "Underline unknown words in red - right click shows suggestions"},
    {"AutoKorrektur", "AutoCorrect"},
    {"Beim Tippen: Satzanfang gross, typografische Anfuehrungszeichen, ... und Gedankenstriche, bekannte Tippfehler. Strg+Z direkt danach nimmt es zurueck.", "While typing: capitalise sentences, typographic quotation marks, ellipsis and dashes, known typos. Ctrl+Z right afterwards takes it back."},
    {"Sprache des Textes", "Language of the text"},
    {"Naechster Fehler", "Next error"},
    {"Zum naechsten unbekannten Wort (F7)", "Go to the next unknown word (F7)"},
    {"Keine Rechtschreibfehler gefunden.", "No spelling errors found."},
    {"Sprache des Textes - fuer Rechtschreibung und AutoKorrektur", "Language of the text - for spelling and AutoCorrect"},
    {"Diese Sprache ist in Windows nicht installiert.", "This language is not installed in Windows."},
    {"Diese Sprache ist in Windows nicht installiert. Hinzufuegen unter Einstellungen > Zeit und Sprache > Sprache und Region.", "This language is not installed in Windows. Add it under Settings > Time & language > Language & region."},
    {"Rechtschreibung pruefen", "Check spelling"},
    {"(keine Vorschlaege)", "(no suggestions)"},
    {"Alle ignorieren", "Ignore all"},
    {"Bis zum Neustart nicht mehr markieren", "Do not mark again until restart"},
    {"Zum Woerterbuch hinzufuegen", "Add to dictionary"},
    {"Gilt dauerhaft als richtig (eigene Liste des Programms)", "Counts as correct from now on (the program's own list)"},
    {"Deutsch (Deutschland)", "German (Germany)"},
    {"Deutsch (Oesterreich)", "German (Austria)"},
    {"Deutsch (Schweiz)", "German (Switzerland)"},
    {"Deutsch (Liechtenstein)", "German (Liechtenstein)"},
    {"Deutsch (Luxemburg)", "German (Luxembourg)"},
    {"Englisch (USA)", "English (US)"},
    {"Englisch (Grossbritannien)", "English (UK)"},
    {"Englisch (Australien)", "English (Australia)"},
    {"Englisch (Kanada)", "English (Canada)"},
    {"Englisch (Irland)", "English (Ireland)"},
    {"Englisch (Indien)", "English (India)"},
    {"Englisch (Neuseeland)", "English (New Zealand)"},
    {"Englisch (Suedafrika)", "English (South Africa)"},
    {"Rechtschreibung und AutoKorrektur", "Spelling and AutoCorrect"},
    {"Review: F7 springt zum naechsten unbekannten Wort.", "Review: F7 jumps to the next unknown word."},
    {"Ueberpruefen > Rechtschreibung: rote Wellen unter unbekannten Woertern, Rechtsklick zeigt Vorschlaege, F7 springt zum naechsten. AutoKorrektur und Sprache daneben oder unten in der Statusleiste.", "Review > Spelling: red waves under unknown words, right click shows suggestions, F7 jumps to the next one. AutoCorrect and language next to it or in the status bar."},
    // ------------------------------------------------ Manuskript: Lineal
    {"Oben / unten", "Top / bottom"},
    {"Links", "Left"},
    {"Rechts", "Right"},
    {"Links und rechts auch direkt im Lineal ziehen.", "Left and right can also be dragged on the ruler."},
    {"Seitenrand links", "Left margin"},
    {"Seitenrand rechts", "Right margin"},
    {"Erste Zeile", "First line"},
    {"Haengender Einzug", "Hanging indent"},
    {"Einzug links", "Left indent"},
    {"Einzug rechts", "Right indent"},
    {"Tabstopp entfernen", "Remove tab stop"},
    {"Tabstopp", "Tab stop"},
    {"Einzug der ersten Zeile", "First line indent"},
    {"Haengender Einzug - die erste Zeile bleibt stehen", "Hanging indent - the first line stays put"},
    {"Einzug links - verschiebt den ganzen Absatz", "Left indent - moves the whole paragraph"},
    {"Tabstopp - ziehen verschiebt, aus dem Lineal ziehen entfernt", "Tab stop - drag to move, drag off the ruler to remove"},
    {"Seitenrand - ziehen, um ihn zu verschieben", "Margin - drag to move it"},
    {"Klicken setzt einen Tabstopp (Alt: ohne Einrasten)", "Click to set a tab stop (Alt: no snapping)"},
    {"Lineal: Einzuege und Tabstopps", "Ruler: indents and tab stops"},
    {"Dreiecke im Lineal ziehen: Einzug der ersten Zeile, haengender und rechter Einzug. Klick ins Lineal setzt einen Tabstopp, herausziehen entfernt ihn. Die Grenze grau/weiss verschiebt den Seitenrand.", "Drag the triangles on the ruler: first line, hanging and right indent. Click the ruler to set a tab stop, drag it off to remove it. The grey/white border moves the margin."},
};
// clang-format on

const std::map<std::string, std::string>& table() {
    static std::map<std::string, std::string> map = [] {
        std::map<std::string, std::string> m;
        for (const Entry& e : kTable) m[e.de] = e.en;
        return m;
    }();
    return map;
}

}  // namespace

Language current() { return g_language; }

void set(Language language) {
    g_language = language;
    setEnglishTexts(language == Language::English);  // Zeitformate im Core
}

const char* name(Language language) {
    return language == Language::English ? "English" : "Deutsch";
}

const char* code(Language language) { return language == Language::English ? "en" : "de"; }

Language fromCode(const std::string& c) {
    return c == "en" ? Language::English : Language::German;
}

const char* tr(const char* german) {
    if (g_language == Language::German || !german) return german;
    const auto& map = table();
    auto it = map.find(german);
    return it == map.end() ? german : it->second.c_str();
}

std::string trs(const char* german) { return tr(german); }

const char* window(const char* german, const char* id) {
    // "Aktionen###actions" - sichtbarer Titel wechselt, die ImGui-ID bleibt
    static std::unordered_map<std::string, std::string> cache;
    std::string key = std::string(id) + "|" + code(g_language);
    auto it = cache.find(key);
    if (it == cache.end())
        it = cache.emplace(key, std::string(tr(german)) + "###" + id).first;
    return it->second.c_str();
}

}  // namespace se::lang
