#include "ui/Lang.h"

#include <map>
#include <string>
#include <unordered_map>

#include "core/Model.h"

namespace se::lang {
namespace {

Language g_language = Language::German;

struct Entry {
    const char* de;
    const char* en;
};

// clang-format off
const Entry kTable[] = {
    // ------------------------------------------------------------- Menues
    {"Datei", "File"},
    {"Bearbeiten", "Edit"},
    {"Ansicht", "View"},
    {"Fenster", "Windows"},
    {"Hilfe", "Help"},
    {"Neues Projekt...", "New project..."},
    {"Projekt oeffnen...", "Open project..."},
    {"Speichern", "Save"},
    {"Alles speichern", "Save all"},
    {"Vault im Explorer oeffnen", "Show vault in Explorer"},
    {"Projekt schliessen", "Close project"},
    {"Beenden", "Quit"},
    {"Rueckgaengig", "Undo"},
    {"Wiederholen", "Redo"},
    {"Rueckgaengig: ", "Undo: "},
    {"Wiederholen: ", "Redo: "},
    {"Rueckgaengig / Wiederholen", "Undo / redo"},
    {"Rueckgaengig: %s", "Undo: %s"},
    {"Wiederholt: ", "Redone: "},
    {"Neue Gruppe...", "New group..."},
    {"Neues Element...", "New element..."},
    {"Neue Aktion...", "New action..."},
    {"Design", "Theme"},
    {"Hell", "Light"},
    {"Dunkel", "Dark"},
    {"Sprache / Language", "Language / Sprache"},
    {"Helles Design aktiv.", "Light theme active."},
    {"Dunkles Design aktiv.", "Dark theme active."},
    {"Sprache: Deutsch", "Language: German"},
    {"Sprache: Englisch", "Language: English"},
    {"Einstellungen / Farben", "Settings / colours"},
    {"Layout zuruecksetzen", "Reset layout"},
    {"Zeilenhoehe Timeline", "Timeline row height"},
    {"Leere Zeitraeume komprimieren", "Compress empty periods"},
    {"Automatisch speichern", "Autosave"},
    {"Gruppen-Manager", "Group manager"},
    {"Details", "Details"},
    {"Aktionen-Panel", "Actions panel"},
    {"Timeline", "Timeline"},
    {"Aktionen", "Actions"},
    {"Story Visualizer", "Story visualizer"},
    {"Connections", "Connections"},
    {"Dateimanager", "File manager"},
    {"Einstellungen", "Settings"},
    {"Tastenkuerzel", "Keyboard shortcuts"},
    {"Ueber Story Editor", "About Story Editor"},
    {"Kein Projekt", "No project"},

    // ------------------------------------------------------- Tastenkuerzel
    {"Strg+N", "Ctrl+N"},
    {"Strg+O", "Ctrl+O"},
    {"Strg+S", "Ctrl+S"},
    {"Strg+G", "Ctrl+G"},
    {"Strg+T", "Ctrl+T"},
    {"Strg+Y", "Ctrl+Y"},
    {"Strg+Z", "Ctrl+Z"},
    {"Strg+Shift+N", "Ctrl+Shift+N"},
    {"Strg+Z / Strg+Y", "Ctrl+Z / Ctrl+Y"},
    {"Strg+Mausrad", "Ctrl+wheel"},
    {"Shift+Mausrad", "Shift+wheel"},
    {"Timeline zoomen", "Zoom the timeline"},
    {"Timeline horizontal scrollen", "Scroll the timeline sideways"},
    {"Doppelklick Timeline", "Double click in timeline"},
    {"Aktion anlegen / bearbeiten", "Create / edit action"},
    {"Ziehen in Timeline", "Drag in timeline"},
    {"Aktion zeitlich verschieben", "Move action in time"},

    // -------------------------------------------------------- Allgemeines
    {"Kein Projekt geoeffnet.", "No project open."},
    {"Kein Projekt geoeffnet. Datei -> Neues Projekt.", "No project open. File -> New project."},
    {"Abbrechen", "Cancel"},
    {"Schliessen", "Close"},
    {"Bearbeiten...", "Edit..."},
    {"Umbenennen...", "Rename..."},
    {"Duplizieren", "Duplicate"},
    {"Loeschen", "Delete"},
    {"Umbenennen", "Rename"},
    {"Umben.", "Rename"},
    {"Suchen...", "Search..."},
    {"Waehlen...", "Browse..."},
    {"Waehlen", "Browse"},
    {"Uebernehmen", "Apply"},
    {"Ja, ausfuehren", "Yes, do it"},
    {"Eingabe", "Input"},
    {"Bestaetigen", "Confirm"},
    {"<keine>", "<none>"},
    {"<keins>", "<none>"},
    {"<oberste Ebene>", "<top level>"},
    {"(Kopie)", "(copy)"},
    {" (Kopie)", " (copy)"},
    {"(?)", "(?)"},
    {"nicht lesbar", "cannot be read"},
    {"Neuer Name", "New name"},
    {"Name eingeben...", "Enter a name..."},
    {"Details anzeigen", "Show details"},
    {"Auswahl leeren", "Clear selection"},
    {"Filter zuruecksetzen", "Reset filters"},
    {"Leeren", "Clear"},
    {"Alle", "All"},
    {"Elemente", "Elements"},
    {"Nichts ausgewaehlt. Element, Aktion oder Gruppe anklicken.",
     "Nothing selected. Click an element, action or group."},

    // ----------------------------------------------------------- Projekte
    {"Neues Projekt", "New project"},
    {"Projektname", "Project name"},
    {"Speicherort (Obsidian-Vault)", "Location (Obsidian vault)"},
    {"Ordner fuer den Vault waehlen", "Choose a folder for the vault"},
    {"Obsidian-Vault waehlen", "Choose an Obsidian vault"},
    {"Es wird die Standard-Struktur (Characters, Locations, Objects, ...) angelegt.",
     "The default structure (Characters, Locations, Objects, ...) will be created."},
    {"Erstellen", "Create"},
    {"In diesem Ordner liegt bereits ein Projekt - es wird geoeffnet.",
     "This folder already holds a project - opening it instead."},
    {"Projekt erstellt: ", "Project created: "},
    {"Projekt geoeffnet: ", "Project opened: "},
    {"Projekt geladen: ", "Project loaded: "},
    {"Projekt geschlossen.", "Project closed."},
    {"Projekt konnte nicht erstellt werden.", "Could not create the project."},
    {"Projekt konnte nicht geladen werden.", "Could not load the project."},
    {"Gespeichert nach ", "Saved to "},

    // ------------------------------------------------------------ Gruppen
    {"+ Gruppe", "+ Group"},
    {"+ Element", "+ Element"},
    {"Neue Gruppe", "New group"},
    {"Gruppe bearbeiten", "Edit group"},
    {"Gruppe bearbeiten (Name/Farbe)...", "Edit group (name/colour)..."},
    {"Uebergeordnete Gruppe", "Parent group"},
    {"Eigene Farbe", "Custom colour"},
    {"Farbe wird automatisch aus der Elterngruppe abgeleitet.",
     "The colour is derived from the parent group automatically."},
    {"Gruppe erstellt", "Group created"},
    {"Gruppe bearbeitet", "Group edited"},
    {"Gruppe geloescht", "Group deleted"},
    {"Gruppe loeschen", "Delete group"},
    {"Gruppe \"", "Group \""},
    {"Gruppe nicht gefunden.", "Group not found."},
    {"Gruppe: ", "Group: "},
    {"Neue Untergruppe...", "New subgroup..."},
    {"Untergruppe", "Subgroup"},
    {"Noch keine Gruppen. Lege eine an: + Gruppe", "No groups yet. Create one: + Group"},
    {" Element(e) inkl. Untergruppen werden mitgeloescht.",
     " element(s) including subgroups will be deleted as well."},
    {"Gruppenfarbe", "Group colour"},
    {"Gruppenfarbe automatisch", "Automatic group colour"},
    {"Gruppen-Farben", "Group colours"},
    {"Auto", "Auto"},
    {"Bitte zuerst eine Gruppe waehlen.", "Please select a group first."},

    // ----------------------------------------------------------- Elemente
    {"Neues Element", "New element"},
    {"Element bearbeiten", "Edit element"},
    {"Element erstellt", "Element created"},
    {"Element bearbeitet", "Element edited"},
    {"Element dupliziert", "Element duplicated"},
    {"Element geloescht", "Element deleted"},
    {"Element umbenannt", "Element renamed"},
    {"Element umbenennen", "Rename element"},
    {"Element verschieben", "Move element"},
    {"Element verschoben", "Element moved"},
    {"Element nach ", "Element moved to "},
    {" verschoben", ""},
    {"Element loeschen", "Delete element"},
    {"Element nicht gefunden.", "Element not found."},
    {"Element suchen...", "Find element..."},
    {"Verschieben nach...", "Move to..."},
    {"Verschieben", "Move"},
    {"Zielgruppe", "Target group"},
    {"\" inklusive .md-Datei loeschen?", "\" including its .md file?"},
    {"Folgende Verweise werden ungueltig:\n", "These references will break:\n"},
    {"Als Aktion in Timeline eintragen", "Add as action to the timeline"},
    {"Datei im Explorer zeigen", "Show file in Explorer"},
    {"Datei oeffnen", "Open file"},
    {"Aktion hinzufuegen", "Add action"},
    {"Erwaehnt in Aktionen", "Mentioned in actions"},
    {"Freitext", "Free text"},
    {"Beziehungen", "Relations"},
    {"Keine Verbindungen.", "No connections."},
    {"+ Verbindung", "+ Connection"},
    {"+ Eigenes Feld", "+ Custom field"},
    {"(nur hier)", "(this element only)"},
    {"Feld nur von diesem Element entfernen", "Remove the field from this element only"},
    {"Legt ein Feld an, das nur zu diesem Element gehoert - das Template der Gruppe bleibt unveraendert.",
     "Creates a field that belongs to this element only - the group template stays untouched."},
    {"Feld entfernt", "Field removed"},
    {"Feld hinzugefuegt", "Field added"},
    {"Feld geaendert", "Field changed"},
    {"Felder", "Fields"},
    {"Feldname", "Field name"},

    // ---------------------------------------------------------- Templates
    {"Template bearbeiten", "Edit template"},
    {"Template bearbeiten...", "Edit template..."},
    {"Template: ", "Template: "},
    {"Template gespeichert", "Template saved"},
    {"Template aktualisiert.", "Template updated."},
    {"Eigene Felder:", "Own fields:"},
    {"Geerbte Felder:", "Inherited fields:"},
    {"Noch keine eigenen Felder.", "No own fields yet."},
    {"+ Neues Feld", "+ New field"},
    {"Neues Feld", "New field"},
    {"Feld bearbeiten", "Edit field"},
    {"Alle speichern", "Save all"},
    {"Speichern ergaenzt fehlende Felder bei allen Elementen dieser Gruppe (inkl. Untergruppen).",
     "Saving adds missing fields to every element of this group (including subgroups)."},
    {"Felder (inkl. geerbt):", "Fields (including inherited):"},
    {"  (geerbt)", "  (inherited)"},
    {"Diese Gruppe hat noch kein Template.", "This group has no template yet."},
    {"Typ", "Type"},
    {"Pflichtfeld", "Required"},
    {"[Pflicht]", "[required]"},
    {"  Pflicht", "  required"},
    {"* Pflicht", "* required"},
    {"Pflichtfelder muessen beim Anlegen eines Elements ausgefuellt werden.",
     "Required fields must be filled in when an element is created."},
    {"Standardwert", "Default value"},
    {"Beschreibung / Hilfetext", "Description / help text"},
    {"Anzeigeformat (optional)", "Display format (optional)"},
    {"Auswahl-Optionen (eine pro Zeile)", "Choices (one per line)"},
    {"Feldname darf nicht leer sein.", "The field name cannot be empty."},
    {"Feldname existiert bereits.", "That field name already exists."},
    {"Name darf nicht leer sein.", "The name cannot be empty."},
    {"Pflichtfeld \"", "Required field \""},
    {"\" ist leer.", "\" is empty."},
    {"z.B. age, birthday, status", "e.g. age, birthday, status"},
    {"z.B. DD.MM.YYYY", "e.g. DD/MM/YYYY"},
    {"Elemente: %d", "Elements: %d"},

    // ----------------------------------------------------------- Aktionen
    {"+ Neue Aktion", "+ New action"},
    {"Neue Aktion", "New action"},
    {"Aktion bearbeiten", "Edit action"},
    {"Aktion erstellt", "Action created"},
    {"Aktion bearbeitet", "Action edited"},
    {"Aktion dupliziert", "Action duplicated"},
    {"Aktion geloescht", "Action deleted"},
    {"Aktion loeschen", "Delete action"},
    {"Aktion \"", "Action \""},
    {"Aktion nicht gefunden.", "Action not found."},
    {"Aktion verschoben", "Action moved"},
    {"Aktion verschoben auf ", "Action moved to "},
    {"Neue Aktion hier", "New action here"},
    {"Neue Aktion fuer dieses Element", "New action for this element"},
    {"Im Aktionen-Panel zeigen", "Show in actions panel"},
    {"In Timeline zeigen", "Show in timeline"},
    {"Zur Timeline", "To timeline"},
    {"Titel", "Title"},
    {"Titel darf nicht leer sein.", "The title cannot be empty."},
    {"Beschreibung / Szene", "Description / scene"},
    {"Beschreibung", "Description"},
    {"wichtig (Major)", "important (major)"},
    {"Strang", "Storyline"},
    {"Zeitpunkt", "Point in time"},
    {"Zeit relativ zu einer anderen Aktion", "Time relative to another action"},
    {"Nach", "After"},
    {"Minuten danach", "minutes later"},
    {"Ergibt: ", "Result: "},
    {"Zeitpunkt nicht lesbar (z.B. \"Tag 5, 14:00\").",
     "Point in time cannot be read (e.g. \"Day 5, 14:00\")."},
    {"Beteiligte Elemente (Charaktere, Orte, Objekte)",
     "Involved elements (characters, locations, objects)"},
    {"Beteiligte", "Involved"},
    {"Beteiligte:", "Involved:"},
    {"Beteiligt: ", "Involved: "},
    {"Beteiligte filtern", "Filter by involved"},
    {"Gewaehlt: ", "Selected: "},
    {"Tags (Komma getrennt, neue einfach eintippen)",
     "Tags (comma separated, just type new ones)"},
    {"Tags: ", "Tags: "},
    {"Tag1, Tag2, ...", "Tag1, Tag2, ..."},
    {"Vorhandene...", "Existing..."},
    {"Noch keine Tags im Projekt - einfach oben eintippen.",
     "No tags in this project yet - just type one above."},
    {"Anhaenge", "Attachments"},
    {"Anhaenge:", "Attachments:"},
    {"Anhaenge: ", "Attachments: "},
    {"Anhaenge waehlen", "Choose attachments"},
    {"Datei hinzufuegen...", "Add file..."},
    {"Entfernen", "Remove"},
    {"Attribut-Aenderungen (Mutations)", "Attribute changes (mutations)"},
    {"Attribut-Aenderungen:", "Attribute changes:"},
    {"+ Aenderung", "+ Change"},
    {"+ Eintrag", "+ Item"},
    {"Zeit: ", "Time: "},
    {"Zeit", "Time"},
    {"#", "#"},
    {"Typ: ", "Type: "},
    {"Handlungsstrang: ", "Storyline: "},
    {"  |  wichtig", "  |  important"},
    {"Volltextsuche...", "Full text search..."},
    {"Zeitraum", "Period"},
    {"%d von %d Aktionen", "%d of %d actions"},
    {"auf", "open"},
    {"zu", "close"},
    {"Eigene Aktions-Typen koennen direkt im Dropdown angelegt werden.",
     "Custom action types can be created right in the dropdown."},
    {"Eigene Handlungsstraenge koennen direkt im Dropdown angelegt werden.",
     "Custom storylines can be created right in the dropdown."},

    // ----------------------------------------------------------- Timeline
    {"Einheit", "Unit"},
    {"Zoom", "Zoom"},
    {"Komprimieren", "Compress"},
    {"Lange Zeitraeume ohne Ereignisse werden zusammengeschoben, dichte Bereiche gedehnt.",
     "Long stretches without events are squeezed together, dense areas are stretched."},
    {"Basis-Zeiteinheit der Skala", "Base time unit of the scale"},
    {"Gruppen-Filter", "Group filter"},
    {"Typ-Filter", "Type filter"},
    {"Sichtbare Hauptgruppen (Mehrfachauswahl)", "Visible top level groups (multiple choice)"},
    {"Zeitfenster", "Time window"},
    {"Keine Spuren sichtbar - Gruppen anlegen oder Filter zuruecksetzen.",
     "No tracks visible - create groups or reset the filters."},

    // ------------------------------------------------------ Story Visualizer
    {"Fokus", "Focus"},
    {"nur Wichtiges", "important only"},
    {"voller Text", "full text"},
    {"Werteaenderungen", "Value changes"},
    {"Nur-Lese-Ansicht: hier wird die Geschichte erzaehlt, nicht bearbeitet.",
     "Read only view: the story is told here, not edited."},
    {"Keine Ereignisse fuer diese Auswahl.", "No events for this selection."},
    {" vergehen", " pass"},
    {" (nicht gezeigte Ereignisse dazwischen)", " (hidden events in between)"},

    // -------------------------------------------------------- Connections
    {"Verbindung erstellen", "Create connection"},
    {"Verbindung bearbeiten", "Edit connection"},
    {"Verbindung erstellt", "Connection created"},
    {"Verbindung bearbeitet", "Connection edited"},
    {"Verbindung geloescht", "Connection deleted"},
    {"Verbindung loeschen", "Delete connection"},
    {"Verbindung nicht gefunden.", "Connection not found."},
    {"Verbindung von hier...", "Connection from here..."},
    {"Diese Verbindung loeschen?", "Delete this connection?"},
    {"Die zwei markierten verbinden", "Connect the two selected"},
    {"Von", "From"},
    {"Nach ", "To "},
    {"Von (Zeit)", "From (time)"},
    {"Bis (Zeit)", "Until (time)"},
    {"Von: ", "From: "},
    {"Bis: ", "Until: "},
    {"offen", "open"},
    {"Block", "Block"},
    {"Bloecke", "Blocks"},
    {"Block erstellen", "Create block"},
    {"Block erstellt", "Block created"},
    {"Block geloescht", "Block deleted"},
    {"Enthaltene Verbindungen:", "Connections in this block:"},
    {"Keine Verbindungen zwischen den markierten Knoten gefunden.",
     "No connections found between the selected nodes."},
    {"Fasst alle Verbindungen zwischen den markierten Knoten zu einem Block zusammen.",
     "Groups every connection between the selected nodes into one block."},
    {"Bloecke fassen zusammengehoerende Verbindungen zusammen - hier auch neu anlegbar.",
     "Blocks group related connections - new ones can be created here too."},
    {"Eigene Beziehungstypen (z.B. mentor_of) koennen direkt im Dropdown angelegt werden.",
     "Custom relation types (e.g. mentor_of) can be created right in the dropdown."},
    {"Auto-Layout", "Auto layout"},
    {"Grad", "Degree"},
    {"Keine Elemente vorhanden.", "No elements yet."},
    {"Linksklick = waehlen (Strg = mehrere), ziehen = verschieben, Rad = Zoom",
     "Left click = select (Ctrl = several), drag = move, wheel = zoom"},

    // ------------------------------------------------------- Dateimanager
    {"Strukturiert", "Structured"},
    {"Rohe Dateien", "Raw files"},
    {"Datei hochladen...", "Upload file..."},
    {"Neuer Ordner...", "New folder..."},
    {"Neuer Ordner", "New folder"},
    {"Vault oeffnen", "Open vault"},
    {"Dateien in den Vault kopieren", "Copy files into the vault"},
    {"Datei waehlen", "Choose a file"},
    {"Keine Datei ausgewaehlt.", "No file selected."},
    {"Im Explorer oeffnen", "Open in Explorer"},
    {"Oeffnen", "Open"},
    {"Datei umbenennen", "Rename file"},
    {"Datei verschieben", "Move file"},
    {"Datei loeschen", "Delete file"},
    {"Datei geloescht.", "File deleted."},
    {"Datei verknuepft", "File linked"},
    {"Datei hinzugefuegt: ", "File added: "},
    {"Zielordner (relativ)", "Target folder (relative)"},
    {"Mit Element verknuepfen:", "Link to element:"},
    {"Verknuepfen", "Link"},
    {"Mit ", "Linked to "},
    {" verknuepft.", "."},
    {"Rohinhalt (nur Ansicht):", "Raw content (view only):"},
    {"Bild konnte nicht geladen werden.", "The image could not be loaded."},
    {"Ordner erstellt: ", "Folder created: "},
    {"Ordner existiert nicht.", "That folder does not exist."},
    {"Ordner ist leer.", "The folder is empty."},
    {"(Vault-Wurzel)", "(vault root)"},
    {"Umbenannt in ", "Renamed to "},
    {"Umbenennen fehlgeschlagen.", "Rename failed."},
    {"Verschieben fehlgeschlagen.", "Move failed."},
    {"Verschoben nach ", "Moved to "},
    {"Loeschen fehlgeschlagen.", "Delete failed."},
    {"Konnte Datei nicht kopieren: ", "Could not copy file: "},
    {"\" wirklich loeschen?", "\" for good?"},
    {"Achtung: .md-Dateien gehoeren zu Elementen. Loeschen kann Verweise brechen.",
     "Careful: .md files belong to elements. Deleting one can break references."},
    {" Datei(en) empfangen - Dateimanager oeffnen.",
     " file(s) received - open the file manager."},

    // ------------------------------------------------------ Einstellungen
    {"Farben", "Colours"},
    {"Text primaer", "Text primary"},
    {"Text sekundaer", "Text secondary"},
    {"Hintergrund", "Background"},
    {"Panel", "Panel"},
    {"Akzent", "Accent"},
    {"Warnung", "Warning"},
    {"Erfolg", "Success"},
    {"Fehler", "Error"},
    {"Timeline Hintergrund", "Timeline background"},
    {"Timeline Raster", "Timeline grid"},
    {"Timeline Spur (alternierend)", "Timeline row (alternating)"},
    {"Timeline Lineal", "Timeline ruler"},
    {"Auswahl", "Selection"},
    {"Hover", "Hover"},
    {"Ghost (Drag)", "Ghost (drag)"},
    {"Verbindungslinie", "Connection line"},
    {"Knoten-Umriss", "Node outline"},
    {"Design neu laden", "Reload theme"},
    {"Verwirft eigene Farbaenderungen und stellt das gewaehlte Design wieder her.",
     "Discards custom colour changes and restores the selected theme."},
    {"Setzt alle Farben auf das gewaehlte Design zurueck. Einzelne Farben lassen sich ",
     "Resets every colour to the selected theme. Individual colours can be "},
    {"darunter weiter anpassen.", "adjusted below."},
    {"Spurhoehe", "Row height"},
    {"Breite Spurtitel", "Track title width"},
    {"Min. Abstand", "Min. spacing"},
    {"Max. Abstand", "Max. spacing"},
    {"Allgemein", "General"},
    {"Schriftgroesse wirkt nach Neustart:", "Font size applies after a restart:"},
    {"Einstellungen speichern", "Save settings"},
    {"Einstellungen gespeichert.", "Settings saved."},
    {"Eigene Listen", "Custom lists"},
    {"Aktions-Typen", "Action types"},
    {"Beziehungstypen", "Relation types"},
    {"Handlungsstraenge", "Storylines"},
    {"Aktions-Typen, Beziehungstypen und Handlungsstraenge gehoeren dir - hier oder direkt ",
     "Action types, relation types and storylines are yours - create them here or right "},
    {"im jeweiligen Dropdown anlegen.", "in the matching dropdown."},
    {"So oft wird der Eintrag im Projekt verwendet.", "How often the entry is used in the project."},
    {"Eintrag umbenennen", "Rename entry"},
    {"Eintrag umbenannt", "Entry renamed"},
    {"Eintrag loeschen", "Delete entry"},
    {"Eintrag geloescht", "Entry deleted"},
    {"Eintrag hinzugefuegt", "Entry added"},
    {"Neuer Eintrag...", "New entry..."},
    {"Eigenen Eintrag hinzufuegen (Enter geht auch)", "Add a custom entry (Enter works too)"},
    {"Eigener Eintrag:", "Custom entry:"},
    {" Eintraege benutzen ihn und werden auf \"",
     " entries use it and will be set to \""},
    {"\" gesetzt.", "\"."},
    {"\" loeschen?", "\"?"},
    {"\" zurueckgesetzt.", "\" restored."},
    {"Design \"", "Theme \""},

    // ------------------------------------------------- Verbindungstypen
    {"Verbindungstypen", "Connection types"},
    {"Verbindungstypen verwalten...", "Manage connection types..."},
    {"Typen verwalten...", "Manage types..."},
    {"Neuer Verbindungstyp", "New connection type"},
    {"Verbindungstyp bearbeiten", "Edit connection type"},
    {"Verbindungstyp erstellt", "Connection type created"},
    {"Verbindungstyp bearbeitet", "Connection type edited"},
    {"Verbindungstyp geloescht", "Connection type deleted"},
    {"Verbindungstyp loeschen", "Delete connection type"},
    {"+ Neuer Typ", "+ New type"},
    {"Noch keine Verbindungstypen.", "No connection types yet."},
    {"Name der Verbindung", "Name of the connection"},
    {"z.B. Person an Ort", "e.g. person at place"},
    {"Rollen - wer oder was wird hier verbunden?", "Roles - who or what is connected here?"},
    {"Pro Rolle festlegen, aus welchen Gruppen gewaehlt werden darf.",
     "For each role, pick which groups may be chosen from."},
    {"Rollenname", "Role name"},
    {"Rolle", "Role"},
    {"+ Rolle", "+ Role"},
    {"alle Gruppen", "all groups"},
    {"Ueber die Timeline setzbar (zeitlich)", "Can be set on the timeline (temporal)"},
    {"Zeitliche Verbindungen gelten ab einem Zeitpunkt, koennen beliebig oft neu gesetzt werden und erscheinen als Band in der Timeline.",
     "Temporal connections apply from a point in time, can be set again as often as you like and "
     "show up as a band in the timeline."},
    {"pro Element nur eine gleichzeitig", "only one at a time per element"},
    {"Beim Setzen einer neuen Verbindung endet die vorherige automatisch - passend z.B. fuer einen Aufenthaltsort.",
     "Setting a new connection ends the previous one automatically - fits a whereabouts, for example."},
    {"Band in der Timeline zeichnen", "Draw a band in the timeline"},
    {"Band laeuft in der Spur von", "Band runs in the track of"},
    {"Beschriftet mit", "Labelled with"},
    {"zeitlich, exklusiv", "temporal, exclusive"},
    {"zeitlich", "temporal"},
    {"fest", "fixed"},
    {" gesetzte Verbindungen werden mitgeloescht.", " connections using it will be deleted as well."},
    {"Eine Vorlage legt fest, was womit verbunden wird - und ob sich das ueber die Zeit aendern darf.",
     "A template decides what gets connected to what - and whether it may change over time."},
    {"Zuerst einen Verbindungstyp anlegen.", "Create a connection type first."},
    {"Ab", "From"},
    {"Bis", "Until"},
    {"leer = von Anfang an", "empty = from the start"},
    {"leer = bis zur naechsten Setzung", "empty = until the next one is set"},
    {"leer = offen", "empty = open ended"},
    {"Baender", "Bands"},
    {"Verbindungen als Band zeigen", "Show connections as a band"},
    {"Setzen: ", "Set: "},
    {"Stand an Tag", "State on day"},
    {"Verbindungstypen sind eigene Vorlagen mit Rollen - sie werden im eigenen Fenster verwaltet.",
     "Connection types are your own templates with roles - they are managed in their own window."},
    // ---------------------------------------------- externe Aenderungen
    {"Externe Aenderung", "External change"},
    {"Die Datei \"%s\" wurde ausserhalb des Programms veraendert!",
     "The file \"%s\" was changed outside of the program!"},
    {"Die Aenderung kann inkonsistent mit den Programm-Daten sein. .md-Dateien sollten nur ueber ",
     "That change may be inconsistent with the program data. .md files should only be edited "},
    {"die UI bearbeitet werden.", "through the UI."},
    {"Inhalt auf der Festplatte:", "Content on disk:"},
    {"Verwirft die Daten im Programm und uebernimmt die Datei.",
     "Discards the data in the program and takes the file."},
    {"Uebernimmt externe Feldwerte, behaelt zusaetzliche Programm-Felder.",
     "Takes external field values, keeps additional program fields."},
    {"Ignoriert die externe Aenderung und schreibt die Programm-Daten zurueck.",
     "Ignores the external change and writes the program data back."},
    {"Externe Datei geladen", "External file loaded"},
    {"Externe Datei zusammengefuehrt", "External file merged"},
    {"Externe Version uebernommen.", "External version applied."},
    {"Zusammengefuehrt.", "Merged."},
    {"Externe Aenderung verworfen.", "External change discarded."},

    // ---------------------------------------------------------- Ueber/Hilfe
    {"Schreib-Management fuer komplexe Geschichten.",
     "Writing management for complex stories."},
    {"Speicherung: Obsidian-Vault (Markdown + JSON)", "Storage: Obsidian vault (Markdown + JSON)"},
    {"Wichtig: .md-Dateien werden ausschliesslich vom Programm geschrieben. Externe ",
     "Important: .md files are written by the program only. External "},
    {"Aenderungen werden erkannt und abgefragt.", "changes are detected and confirmed with you."},
    {"DirectX 11 konnte nicht initialisiert werden.", "DirectX 11 could not be initialised."},
};
// clang-format on

const std::map<std::string, std::string>& table() {
    static std::map<std::string, std::string> map = [] {
        std::map<std::string, std::string> m;
        for (const Entry& e : kTable) m[e.de] = e.en;
        return m;
    }();
    return map;
}

}  // namespace

Language current() { return g_language; }

void set(Language language) {
    g_language = language;
    setEnglishTexts(language == Language::English);  // Zeitformate im Core
}

const char* name(Language language) {
    return language == Language::English ? "English" : "Deutsch";
}

const char* code(Language language) { return language == Language::English ? "en" : "de"; }

Language fromCode(const std::string& c) {
    return c == "en" ? Language::English : Language::German;
}

const char* tr(const char* german) {
    if (g_language == Language::German || !german) return german;
    const auto& map = table();
    auto it = map.find(german);
    return it == map.end() ? german : it->second.c_str();
}

std::string trs(const char* german) { return tr(german); }

const char* window(const char* german, const char* id) {
    // "Aktionen###actions" - sichtbarer Titel wechselt, die ImGui-ID bleibt
    static std::unordered_map<std::string, std::string> cache;
    std::string key = std::string(id) + "|" + code(g_language);
    auto it = cache.find(key);
    if (it == cache.end())
        it = cache.emplace(key, std::string(tr(german)) + "###" + id).first;
    return it->second.c_str();
}

}  // namespace se::lang
